require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const { connectDB, getDB } = require('../config/db');
const User = require('../models/User');
const Poet = require('../models/Poet');
const Poetry = require('../models/Poetry');
const Course = require('../models/Course');
const Qafiya = require('../models/Qafiya');

function seed() {
  connectDB();
  const db = getDB();
  console.log('Connected to SQLite');

  // Clear existing data
  db.exec(`
    DELETE FROM qafiya;
    DELETE FROM courses;
    DELETE FROM poetry;
    DELETE FROM poets;
    DELETE FROM users;
  `);
  console.log('Cleared existing data');

  // ─── Users ───────────────────────────────────────────────────────────────────
  User.create({ name: 'Admin', email: 'zauqesukhn@gmail.com', password: 'iamthebossofz@uqesukhn110', role: 'admin' });
  User.create({ name: 'Test User', email: 'test@zauqesukhn.com', password: 'test123', role: 'user' });
  console.log('Users created');

  // ─── Poets ───────────────────────────────────────────────────────────────────
  const ghalib  = Poet.create({ name: 'Mirza Ghalib',   nameUrdu: 'مرزا غالب',   bio: 'Mirza Asadullah Baig Khan, known by his pen name Ghalib, was the most prominent Urdu and Persian poet during the last years of the Mughal Empire. His poetry is celebrated for its depth of thought, sophisticated wit, and mastery of language.', bioUrdu: 'مرزا اسداللہ بیگ خان جو غالب کے تخلص سے مشہور ہیں، مغل سلطنت کے آخری دور کے سب سے نمایاں اردو اور فارسی شاعر تھے۔ ان کی شاعری فکر کی گہرائی، پُرلطف ظرافت اور زبان پر دسترس کے لیے مشہور ہے۔', era: '1797–1869', eraUrdu: '۱۷۹۷–۱۸۶۹', style: 'Classical Ghazal, Persian-influenced Urdu poetry', styleUrdu: 'کلاسیکل غزل، فارسی اثرات والی اردو شاعری', imageUrl: '' });
  const iqbal   = Poet.create({ name: 'Allama Iqbal',   nameUrdu: 'علامہ اقبال',  bio: 'Sir Muhammad Iqbal, widely known as Allama Iqbal, was a poet, philosopher, and politician. He is considered the spiritual father of Pakistan.', bioUrdu: 'سر محمد اقبال جو علامہ اقبال کے نام سے مشہور ہیں، شاعر، فلسفی اور سیاستدان تھے۔ انہیں پاکستان کا روحانی باپ سمجھا جاتا ہے۔', era: '1877–1938', eraUrdu: '۱۸۷۷–۱۹۳۸', style: 'Philosophical poetry, Khudi (Self), Pan-Islamism', styleUrdu: 'فلسفیانہ شاعری، خودی، پان اسلامیت', imageUrl: '' });
  const faiz    = Poet.create({ name: 'Faiz Ahmed Faiz', nameUrdu: 'فیض احمد فیض', bio: 'Faiz Ahmed Faiz was a Pakistani poet who blended the classical tradition of Urdu poetry with Marxist ideas to create revolutionary yet deeply lyrical verse.', bioUrdu: 'فیض احمد فیض پاکستانی شاعر تھے جنہوں نے اردو شاعری کی کلاسیکل روایت کو مارکسی نظریات کے ساتھ ملا کر انقلابی مگر گہری غنائی شاعری تخلیق کی۔', era: '1911–1984', eraUrdu: '۱۹۱۱–۱۹۸۴', style: 'Progressive, Revolutionary, Romantic', styleUrdu: 'ترقی پسند، انقلابی، رومانوی', imageUrl: '' });
  const mir     = Poet.create({ name: 'Mir Taqi Mir',   nameUrdu: 'میر تقی میر',  bio: 'Mir Taqi Mir is considered one of the pillars of the Urdu ghazal tradition, revered as the "God of Poetry" (Khuda-e-Sukhn). His ghazals are marked by simplicity, pathos, and profound emotion.', bioUrdu: 'میر تقی میر اردو غزل کی روایت کے ستونوں میں سے ایک سمجھے جاتے ہیں، جنہیں خدائے سخن کہا جاتا ہے۔', era: '1723–1810', eraUrdu: '۱۷۲۳–۱۸۱۰', style: 'Classical Ghazal, melancholic simplicity', styleUrdu: 'کلاسیکل غزل، غمگین سادگی', imageUrl: '' });
  const faraz   = Poet.create({ name: 'Ahmad Faraz',    nameUrdu: 'احمد فراز',    bio: 'Ahmad Faraz was a Pakistani Urdu poet known for his romantic and progressive poetry. His ghazals and nazms are widely read across South Asia.', bioUrdu: 'احمد فراز پاکستانی اردو شاعر تھے جو اپنی رومانوی اور ترقی پسند شاعری کے لیے مشہور تھے۔', era: '1931–2008', eraUrdu: '۱۹۳۱–۲۰۰۸', style: 'Romantic Ghazal, Progressive poetry', styleUrdu: 'رومانوی غزل، ترقی پسند شاعری', imageUrl: '' });
  const parveen = Poet.create({ name: 'Parveen Shakir', nameUrdu: 'پروین شاکر',   bio: 'Parveen Shakir was a Pakistani poet acclaimed for her modern Urdu ghazals and nazms that speak of love, longing, and feminine sensibility.', bioUrdu: 'پروین شاکر پاکستانی شاعرہ تھیں جو اپنی جدید اردو غزلوں اور نظموں کے لیے مشہور ہیں۔', era: '1952–1994', eraUrdu: '۱۹۵۲–۱۹۹۴', style: 'Modern Ghazal, feminine sensibility', styleUrdu: 'جدید غزل، نسائی احساس', imageUrl: '' });
  const jaun    = Poet.create({ name: 'Jaun Elia',      nameUrdu: 'جون ایلیا',    bio: 'Jaun Elia was a Pakistani Urdu poet known for his unconventional style, existential themes, and raw emotional intensity.', bioUrdu: 'جون ایلیا پاکستانی اردو شاعر تھے جو اپنے غیر روایتی انداز اور وجودی موضوعات کے لیے مشہور ہیں۔', era: '1931–2002', eraUrdu: '۱۹۳۱–۲۰۰۲', style: 'Existential, unconventional, introspective', styleUrdu: 'وجودی، غیر روایتی، خود شناسی', imageUrl: '' });
  const insha   = Poet.create({ name: 'Ibn-e-Insha',    nameUrdu: 'ابنِ انشاء',   bio: 'Ibn-e-Insha (Sher Muhammad Khan) was a Pakistani Urdu poet, travel writer, and humorist famous for witty, satirical, and melancholic romantic verse.', bioUrdu: 'ابن انشاء (شیر محمد خان) پاکستانی اردو شاعر، سفرنامہ نگار اور مزاح نگار تھے۔', era: '1927–1978', eraUrdu: '۱۹۲۷–۱۹۷۸', style: 'Humorous, satirical, romantic', styleUrdu: 'مزاحیہ، طنزیہ، رومانوی', imageUrl: '' });
  const anees   = Poet.create({ name: 'Mir Anees',      nameUrdu: 'میر انیس',     bio: 'Mir Anees was an Urdu poet of the 19th century and one of the greatest masters of the marsiya (elegy). His tragic poetry and highly ornate style made him legendary.', bioUrdu: 'میر انیس اٹھارہویں صدی کے اردو شاعر تھے اور مرثیے کے عظیم ترین استاد۔', era: '1802–1874', eraUrdu: '۱۸۰۲–۱۸۷۴', style: 'Marsiya (Elegy), Tragic, Ornate', styleUrdu: 'مرثیہ، المناک، آرائش پذیر', imageUrl: '' });
  const josh    = Poet.create({ name: 'Josh Malihabadi', nameUrdu: 'جوش ملیح آبادی', bio: 'Josh Malihabadi was an exceptional Urdu poet, writer and freedom fighter. His poetry is filled with patriotic fervor and revolutionary spirit.', bioUrdu: 'جوش ملیح آبادی ایک بہترین اردو شاعر، مصنف اور آزادی کے سپاہی تھے۔', era: '1884–1951', eraUrdu: '۱۸۸۴–۱۹۵۱', style: 'Patriotic, Revolutionary, Explosive', styleUrdu: 'وطن پرستانہ، انقلابی، دھماکہ خیز', imageUrl: '' });
  console.log('10 poets created');

  // ─── Poetry ──────────────────────────────────────────────────────────────────
  const poetryData = [
    // Ghalib
    { title: 'Hazaron Khwahishein', titleUrdu: 'ہزاروں خواہشیں ایسی', type: 'ghazal', poet: ghalib.id, content: 'ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے\nبہت نکلے میرے ارمان لیکن پھر بھی کم نکلے', contentLines: ['ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے', 'بہت نکلے میرے ارمان لیکن پھر بھی کم نکلے', 'ڈرے کیوں میرا قاتل کیا رہے گا اس کا اگر', 'وہی ہوگی جو چاہے یا مری نکلے کہ دم نکلے'], tags: ['خواہش', 'ارمان', 'غزل', 'غالب'], isFeatured: true },
    { title: 'Dil-e-Nadaan', titleUrdu: 'دلِ ناداں', type: 'ghazal', poet: ghalib.id, content: 'دلِ ناداں تجھے ہوا کیا ہے\nآخر اس درد کی دوا کیا ہے', contentLines: ['دلِ ناداں تجھے ہوا کیا ہے', 'آخر اس درد کی دوا کیا ہے', 'ہم ہیں مشتاق اور وہ بیزار', 'یا الٰہی یہ ماجرا کیا ہے'], tags: ['دل', 'درد', 'غزل'], isFeatured: true },
    { title: 'Ishq Par Zor Nahin', titleUrdu: 'عشق پر زور نہیں', type: 'sher', poet: ghalib.id, content: 'عشق پر زور نہیں ہے یہ وہ آتش غالب\nکہ لگائے نہ لگے اور بجھائے نہ بنے', contentLines: ['عشق پر زور نہیں ہے یہ وہ آتش غالب', 'کہ لگائے نہ لگے اور بجھائے نہ بنے'], tags: ['عشق', 'آتش', 'غالب'], isFeatured: false },
    { title: 'Aah Ko Chahiye', titleUrdu: 'آہ کو چاہیے', type: 'sher', poet: ghalib.id, content: 'آہ کو چاہیے اک عمر اثر ہونے تک\nکون جیتا ہے تری زلف کے سر ہونے تک', contentLines: ['آہ کو چاہیے اک عمر اثر ہونے تک', 'کون جیتا ہے تری زلف کے سر ہونے تک'], tags: ['آہ', 'عمر', 'زلف'], isFeatured: false },
    { title: 'Dard Ka Hissa', titleUrdu: 'درد کا حصہ', type: 'sher', poet: ghalib.id, content: 'درد کا حد سے گزرنا ہے دوا ہو جانا\nیعنی جب اتنا درد ہو تو درد ہی دوا ہو جانا', contentLines: ['درد کا حد سے گزرنا ہے دوا ہو جانا', 'یعنی جب اتنا درد ہو تو درد ہی دوا ہو جانا'], tags: ['درد', 'غالب', 'شعر'], isFeatured: false },
    // Iqbal
    { title: 'Khudi Ko Kar Buland', titleUrdu: 'خودی کو کر بلند', type: 'sher', poet: iqbal.id, content: 'خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے\nخدا بندے سے خود پوچھے بتا تیری رضا کیا ہے', contentLines: ['خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے', 'خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے'], tags: ['خودی', 'خدا', 'اقبال', 'فلسفہ'], isFeatured: true },
    { title: 'Lab Pe Aati Hai Dua', titleUrdu: 'لب پے آتی ہے دعا', type: 'nazm', poet: iqbal.id, content: 'لب پے آتی ہے دعا بن کے تمنا میری\nزندگی شمع کی صورت ہو خدایا میری', contentLines: ['لب پے آتی ہے دعا بن کے تمنا میری', 'زندگی شمع کی صورت ہو خدایا میری', 'ہو میرے دم سے یونہی میرے وطن کی زینت', 'جیسے ہوتی ہے چمن سے گلِ تر کی زینت'], tags: ['دعا', 'وطن', 'اقبال', 'نظم'], isFeatured: true },
    { title: 'Sitaron Se Aage', titleUrdu: 'ستاروں سے آگے', type: 'nazm', poet: iqbal.id, content: 'ستاروں سے آگے جہاں اور بھی ہیں\nابھی عشق کے امتحاں اور بھی ہیں', contentLines: ['ستاروں سے آگے جہاں اور بھی ہیں', 'ابھی عشق کے امتحاں اور بھی ہیں', 'تہی زندگی سے نہیں یہ فضائیں', 'یہاں سینکڑوں کارواں اور بھی ہیں'], tags: ['ستارے', 'اقبال', 'عشق', 'کہکشاں'], isFeatured: true },
    // Faiz
    { title: 'Mujh Se Pehli Si Muhabbat', titleUrdu: 'مجھ سے پہلی سی محبت', type: 'ghazal', poet: faiz.id, content: 'مجھ سے پہلی سی محبت میرے محبوب نہ مانگ\nمیں نے سمجھا تھا کہ تو ہے تو درخشاں ہے حیات', contentLines: ['مجھ سے پہلی سی محبت میرے محبوب نہ مانگ', 'میں نے سمجھا تھا کہ تو ہے تو درخشاں ہے حیات', 'تیرا غم ہے تو غمِ دہر کا جھگڑا کیا ہے', 'اور بھی دکھ ہیں زمانے میں محبت کے سوا'], tags: ['محبت', 'فیض', 'غزل', 'رومانس'], isFeatured: true },
    { title: 'Hum Dekhenge', titleUrdu: 'ہم دیکھیں گے', type: 'nazm', poet: faiz.id, content: 'ہم دیکھیں گے\nلازم ہے کہ ہم بھی دیکھیں گے\nوہ دن کہ جس کا وعدہ ہے', contentLines: ['ہم دیکھیں گے', 'لازم ہے کہ ہم بھی دیکھیں گے', 'وہ دن کہ جس کا وعدہ ہے', 'جو لوحِ ازل میں لکھا ہے', 'جب ظلم و ستم کے کوہِ گراں', 'روئی کی طرح اڑ جائیں گے'], tags: ['انقلاب', 'فیض', 'نظم', 'ترقی پسند'], isFeatured: true },
    { title: 'Gulon Mein Rang Bhare', titleUrdu: 'گلوں میں رنگ بھرے', type: 'ghazal', poet: faiz.id, content: 'گلوں میں رنگ بھرے باد نوبہار چلے\nچلے بھی آؤ کہ گلشن کا کاروبار چلے', contentLines: ['گلوں میں رنگ بھرے باد نوبہار چلے', 'چلے بھی آؤ کہ گلشن کا کاروبار چلے', 'قفس اداس ہے یارو صبا سے کچھ تو کہو', 'کہیں تو بہرِ خدا آج ذکرِ یار چلے'], tags: ['گل', 'بہار', 'فیض', 'غزل'], isFeatured: false },
    // Mir
    { title: 'Mir Woh Neem Baaz Aankhein', titleUrdu: 'میر وہ نیم باز آنکھیں', type: 'sher', poet: mir.id, content: 'میر ان نیم باز آنکھوں میں\nساری مستی شراب کی سی ہے', contentLines: ['میر ان نیم باز آنکھوں میں', 'ساری مستی شراب کی سی ہے'], tags: ['آنکھ', 'مستی', 'میر', 'غزل'], isFeatured: true },
    { title: 'Patta Patta Buta Buta', titleUrdu: 'پتہ پتہ بوٹا بوٹا', type: 'ghazal', poet: mir.id, content: 'پتہ پتہ بوٹا بوٹا حال ہمارا جانے ہے\nجانے نہ جانے گل ہی نہ جانے باغ تو سارا جانے ہے', contentLines: ['پتہ پتہ بوٹا بوٹا حال ہمارا جانے ہے', 'جانے نہ جانے گل ہی نہ جانے باغ تو سارا جانے ہے'], tags: ['باغ', 'میر', 'غزل', 'کلاسیک'], isFeatured: false },
    // Faraz
    { title: 'Ranjish Hi Sahi', titleUrdu: 'رنجش ہی سہی', type: 'ghazal', poet: faraz.id, content: 'رنجش ہی سہی دل ہی دکھانے کے لیے آ\nآ پھر سے مجھے چھوڑ کے جانے کے لیے آ', contentLines: ['رنجش ہی سہی دل ہی دکھانے کے لیے آ', 'آ پھر سے مجھے چھوڑ کے جانے کے لیے آ', 'پہلے سے مراسم نہ سہی پھر بھی کبھی تو', 'رسمِ راہِ دنیا ہی نبھانے کے لیے آ'], tags: ['رنجش', 'فراز', 'غزل', 'رومانس'], isFeatured: true },
    { title: 'Ab Ke Hum Bichde', titleUrdu: 'اب کے ہم بچھڑے', type: 'sher', poet: faraz.id, content: 'اب کے ہم بچھڑے تو شاید کبھی خوابوں میں ملیں\nجیسے سوکھے ہوئے پھول کتابوں میں ملیں', contentLines: ['اب کے ہم بچھڑے تو شاید کبھی خوابوں میں ملیں', 'جیسے سوکھے ہوئے پھول کتابوں میں ملیں'], tags: ['جدائی', 'فراز', 'شعر', 'محبت'], isFeatured: false },
    { title: 'Wafa Kaisi', titleUrdu: 'وفا کیسی', type: 'sher', poet: faraz.id, content: 'وفا کیسی کہاں کا عشق جب سر پھوڑنا ٹھہرا\nتو پھر اے سنگدل تیرا ہی در کیوں چھوڑنا ٹھہرا', contentLines: ['وفا کیسی کہاں کا عشق جب سر پھوڑنا ٹھہرا', 'تو پھر اے سنگدل تیرا ہی در کیوں چھوڑنا ٹھہرا'], tags: ['وفا', 'فراز', 'عشق'], isFeatured: false },
    // Parveen
    { title: 'Khushbu', titleUrdu: 'خوشبو', type: 'nazm', poet: parveen.id, content: 'وہ خوشبو لے کے آئی تھی ہوا میرے لیے\nمیں ڈھونڈتی رہی اس کو تمام رات', contentLines: ['وہ خوشبو لے کے آئی تھی ہوا میرے لیے', 'میں ڈھونڈتی رہی اس کو تمام رات'], tags: ['خوشبو', 'پروین', 'نظم', 'محبت'], isFeatured: false },
    { title: 'Tum Meri Zindagi', titleUrdu: 'تم میری زندگی', type: 'nazm', poet: parveen.id, content: 'تم میری زندگی ہو\nاور زندگی تمہاری\nیہ ربط ہی ہمارا عجب ہے', contentLines: ['تم میری زندگی ہو', 'اور زندگی تمہاری', 'یہ ربط ہی ہمارا عجب ہے', 'جو جدا ہو کے بھی جدا نہیں'], tags: ['پروین', 'نظم', 'زندگی', 'محبت'], isFeatured: false },
    // Jaun
    { title: 'Mujhe Bhool Jana', titleUrdu: 'مجھے بھول جانا', type: 'ghazal', poet: jaun.id, content: 'مجھے بھول جانا آسان ہوگا\nتمہیں یاد رکھنا مشکل تھا', contentLines: ['مجھے بھول جانا آسان ہوگا', 'تمہیں یاد رکھنا مشکل تھا'], tags: ['جون', 'غزل', 'یاد', 'جدائی'], isFeatured: false },
    { title: 'Kuch Aur Chahiye', titleUrdu: 'کچھ اور چاہیے', type: 'ghazal', poet: jaun.id, content: 'کچھ اور چاہیے وسعت میرے بیاں کے لیے\nزمیں تنگ پڑ گئی ہے میرے آسمان کے لیے', contentLines: ['کچھ اور چاہیے وسعت میرے بیاں کے لیے', 'زمیں تنگ پڑ گئی ہے میرے آسمان کے لیے'], tags: ['جون', 'غزل', 'آسمان'], isFeatured: false },
    // Ibn-e-Insha
    { title: 'Insha Ji Uthho', titleUrdu: 'انشا جی اٹھو', type: 'nazm', poet: insha.id, content: 'انشا جی اٹھو اب کوچ کرو اس شہر میں جی کو کیا لگانا\nجس شہر میں یار نہ ہو اپنا وہ شہر ہمیں کیا یاد رہے گا', contentLines: ['انشا جی اٹھو اب کوچ کرو اس شہر میں جی کو کیا لگانا', 'جس شہر میں یار نہ ہو اپنا وہ شہر ہمیں کیا یاد رہے گا'], tags: ['انشا', 'نظم', 'سفر', 'یاد'], isFeatured: false },
    { title: 'Abhi Tak Yaad Hai', titleUrdu: 'ابھی تک یاد ہے', type: 'ghazal', poet: insha.id, content: 'ابھی تک یاد ہے مجھ کو وہ پہلی ملاقات\nوہ شام کی روشنی وہ چاند رات', contentLines: ['ابھی تک یاد ہے مجھ کو وہ پہلی ملاقات', 'وہ شام کی روشنی وہ چاند رات'], tags: ['انشا', 'غزل', 'یاد', 'رومانس'], isFeatured: false },
    // Mir Anees
    { title: 'Karbala Ka Qissa', titleUrdu: 'کربلا کا قصہ', type: 'sher', poet: anees.id, content: 'حسین کے شہادت کا قصہ سناتے ہیں\nہر شام یہ غم و حزن دہرالتے ہیں', contentLines: ['حسین کے شہادت کا قصہ سناتے ہیں', 'ہر شام یہ غم و حزن دہرالتے ہیں'], tags: ['میر انیس', 'مرثیہ', 'کربلا'], isFeatured: false },
    { title: 'Ali Ka Wafada', titleUrdu: 'علی کا وفادہ', type: 'sher', poet: anees.id, content: 'علی نے دیے تخت و تاج کو چھوڑ کر\nخون میں نہالے سر اپنے کو', contentLines: ['علی نے دیے تخت و تاج کو چھوڑ کر', 'خون میں نہالے سر اپنے کو'], tags: ['میر انیس', 'وفاداری', 'قربانی'], isFeatured: false },
    // Josh Malihabadi
    { title: 'Hind Ka Pur Josh Nara', titleUrdu: 'ہند کا پرجوش نعرہ', type: 'sher', poet: josh.id, content: 'ہند کا پرجوش نعرہ لگا\nوقت آیا ہے اب جاگ جاگ', contentLines: ['ہند کا پرجوش نعرہ لگا', 'وقت آیا ہے اب جاگ جاگ'], tags: ['جوش', 'وطن پرستی', 'انقلاب'], isFeatured: false },
    { title: 'Azadi Ka Nara', titleUrdu: 'آزادی کا نعرہ', type: 'sher', poet: josh.id, content: 'آزادی آزادی کا نعرہ ہو\nہر سینے میں یہ آگ لگو', contentLines: ['آزادی آزادی کا نعرہ ہو', 'ہر سینے میں یہ آگ لگو'], tags: ['جوش', 'آزادی', 'انقلاب'], isFeatured: false },
  ];
  poetryData.forEach(p => Poetry.create(p));
  console.log(`${poetryData.length} poetry entries created`);

  // ─── Courses ─────────────────────────────────────────────────────────────────
  const coursesData = [
    { title: 'Introduction to Urdu Poetry', titleUrdu: 'اردو شاعری کا تعارف', description: 'A beginner-friendly course introducing the world of Urdu poetry, its history, and key terms.', descriptionUrdu: 'اردو شاعری کی دنیا، اس کی تاریخ اور اہم اصطلاحات سے آگاہی کا ابتدائی کورس', order: 1, isPublished: true, lessons: [{ title: 'What is Urdu Poetry?', titleUrdu: 'اردو شاعری کیا ہے؟', content: 'Urdu poetry is one of the richest literary traditions in the world, combining Persian and Arabic influences with indigenous South Asian culture.', contentUrdu: 'اردو شاعری دنیا کی سب سے امیر ادبی روایات میں سے ایک ہے۔', examples: [{ urdu: 'ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے', poet: 'مرزا غالب', translation: 'Thousands of desires, each worth dying for' }], duration: '20 min' }, { title: 'History of Urdu Poetry', titleUrdu: 'اردو شاعری کی تاریخ', content: 'Urdu poetry evolved over centuries from the courts of the Mughals to the salons of Lucknow and Delhi.', contentUrdu: 'اردو شاعری مغلوں کے دربار سے لکھنو اور دہلی کے محفل خانوں تک صدیوں میں پروان چڑھی۔', examples: [], duration: '25 min' }] },
    { title: 'Mastering the Ghazal', titleUrdu: 'غزل کی مہارت', description: 'Deep dive into the most beloved form of Urdu poetry — the Ghazal.', descriptionUrdu: 'اردو شاعری کی سب سے پیاری صنف — غزل — میں گہرائی سے اترنا', order: 2, isPublished: true, lessons: [{ title: 'Structure of a Ghazal', titleUrdu: 'غزل کی ساخت', content: "A Ghazal consists of couplets (she'ar) that are independent yet thematically connected. The last couplet (maqta) contains the poet's pen name (takhallus).", contentUrdu: 'غزل اشعار پر مشتمل ہوتی ہے۔ آخری شعر (مقطع) میں شاعر کا تخلص ہوتا ہے۔', examples: [{ urdu: 'رنجش ہی سہی دل ہی دکھانے کے لیے آ', poet: 'احمد فراز', translation: 'Come even if it is just to hurt my heart' }], duration: '30 min' }, { title: 'Radif and Qafia in Ghazal', titleUrdu: 'غزل میں ردیف اور قافیہ', content: 'Radif is the repeated word or phrase at the end of each couplet. Qafia is the rhyming pattern preceding the Radif.', contentUrdu: 'ردیف ہر شعر کے آخر میں دہرایا جانے والا لفظ یا جملہ ہے۔ قافیہ ردیف سے پہلے آنے والا ہم آواز الفاظ کا نظام ہے۔', examples: [{ urdu: 'گلوں میں رنگ بھرے باد نوبہار چلے', poet: 'فیض احمد فیض', translation: 'Fill color in the flowers, let the spring breeze blow' }], duration: '35 min' }] },
    { title: 'The Art of Nazm', titleUrdu: 'نظم کا فن', description: 'Explore the free-verse form of Urdu poetry — the Nazm.', descriptionUrdu: 'اردو شاعری کی آزاد نظم اور اس کے ارتقا کو دریافت کریں', order: 3, isPublished: true, lessons: [{ title: 'What is a Nazm?', titleUrdu: 'نظم کیا ہے؟', content: 'A Nazm deals with a single unified theme. Unlike Ghazal, each verse of a Nazm is connected to the other.', contentUrdu: 'نظم ایک واحد متحدہ موضوع سے متعلق ہوتی ہے۔ غزل کے برعکس، نظم کا ہر مصرعہ دوسرے سے جڑا ہوتا ہے۔', examples: [{ urdu: 'ہم دیکھیں گے', poet: 'فیض احمد فیض', translation: 'We shall witness' }], duration: '25 min' }] },
    { title: 'Qasida: The Ode', titleUrdu: 'قصیدہ: مدحیہ شاعری', description: 'Learn about the Qasida — the classical form of praise poetry.', descriptionUrdu: 'قصیدہ سیکھیں — اردو ادب میں مدحیہ شاعری کی کلاسیکل صنف', order: 4, isPublished: true, lessons: [{ title: 'Introduction to Qasida', titleUrdu: 'قصیدے کا تعارف', content: 'Qasida is a long panegyric poem written in praise of a king, patron, or religious figure.', contentUrdu: 'قصیدہ کلاسیکی اردو ادب میں ایک طویل مدحیہ نظم ہے۔', examples: [], duration: '30 min' }] },
    { title: 'Marsiya: Elegies in Urdu', titleUrdu: 'مرثیہ: اردو میں نوحہ', description: 'A study of Marsiya — the elegy form.', descriptionUrdu: 'مرثیے کا مطالعہ — نوحہ کی صنف', order: 5, isPublished: true, lessons: [{ title: 'Origins of Marsiya', titleUrdu: 'مرثیے کی ابتداء', content: 'Marsiya in Urdu literature is deeply connected to the tragedy of Karbala. Mir Anis and Mirza Dabeer are its greatest masters.', contentUrdu: 'اردو ادب میں مرثیہ کا گہرا تعلق کربلا کے المیے سے ہے۔ میر انیس اور مرزا دبیر اس کے سب سے بڑے استاد ہیں۔', examples: [], duration: '40 min' }] },
    { title: 'Rubai and Masnavi', titleUrdu: 'رباعی اور مثنوی', description: 'Explore the Rubai (quatrain) and Masnavi (narrative poem) forms.', descriptionUrdu: 'رباعی اور مثنوی کی اصناف کو دریافت کریں', order: 6, isPublished: true, lessons: [{ title: 'The Rubai Form', titleUrdu: 'رباعی کی صنف', content: 'A Rubai is a four-line verse (quatrain) with rhyme scheme AABA. Best known through Omar Khayyam.', contentUrdu: 'رباعی ایک چار مصرعی نظم ہے جس کا قافیہ بندی کا نظام AABA ہے۔', examples: [], duration: '25 min' }] },
    { title: 'Beher and Meter in Urdu Poetry', titleUrdu: 'بحر اور وزن اردو شاعری میں', description: 'Understand the metrical system (Beher) that governs Urdu classical poetry.', descriptionUrdu: 'وہ وزنی نظام (بحر) سمجھیں جو اردو کلاسیکل شاعری پر حاوی ہے', order: 7, isPublished: true, lessons: [{ title: 'What is Beher?', titleUrdu: 'بحر کیا ہے؟', content: 'Beher is the metrical framework of Urdu poetry. Each poem must conform to a specific pattern of long and short syllables called Arkaan.', contentUrdu: 'بحر اردو شاعری کا وزنی ڈھانچہ ہے۔ ہر نظم کو ارکان کے مخصوص نمونے کے مطابق ہونا ضروری ہے۔', examples: [], duration: '45 min' }] },
    { title: 'Qafiya and Radif: Rhyme in Urdu Poetry', titleUrdu: 'قافیہ اور ردیف: اردو شاعری میں قافیہ بندی', description: 'Master the system of rhyme (Qafiya) and refrain (Radif).', descriptionUrdu: 'اردو شاعری میں قافیہ اور ردیف کے نظام میں مہارت حاصل کریں', order: 8, isPublished: true, lessons: [{ title: 'Qafiya Explained', titleUrdu: 'قافیہ کی وضاحت', content: 'Qafiya refers to the rhyming words at the end of lines. The rules of Qafiya are precise.', contentUrdu: 'قافیہ سے مراد مصرعوں کے آخر میں ہم آواز الفاظ ہیں۔ قافیے کے قواعد دقیق ہوتے ہیں۔', examples: [{ urdu: 'دلِ ناداں تجھے ہوا کیا ہے / آخر اس درد کی دوا کیا ہے', poet: 'مرزا غالب', translation: 'What has happened to you, naive heart / What is the cure for this pain' }], duration: '40 min' }] },
    { title: 'Tashbih and Istiara: Urdu Figures of Speech', titleUrdu: 'تشبیہ اور استعارہ: اردو میں صنائع بدائع', description: 'Learn the figures of speech that enrich Urdu poetry.', descriptionUrdu: 'وہ صنائع بدائع سیکھیں جو اردو شاعری کو مالا مال کرتے ہیں', order: 9, isPublished: true, lessons: [{ title: 'Tashbih (Simile)', titleUrdu: 'تشبیہ', content: 'Tashbih is the comparison of one thing to another using words like "like" or "as". It is the most common device in Urdu poetry.', contentUrdu: 'تشبیہ ایک چیز کا دوسری چیز سے موازنہ ہے۔ یہ اردو شاعری میں سب سے عام صنعت ہے۔', examples: [{ urdu: 'اب کے ہم بچھڑے تو شاید کبھی خوابوں میں ملیں / جیسے سوکھے ہوئے پھول کتابوں میں ملیں', poet: 'احمد فراز', translation: 'If we part now, we may meet only in dreams / Like dried flowers found in books' }], duration: '35 min' }] },
    { title: 'Arooz: The Science of Urdu Prosody', titleUrdu: 'عروض: اردو شاعری کا علم', description: 'An advanced course on Arooz — the formal science governing the meters of classical Urdu poetry.', descriptionUrdu: 'عروض پر ایک اعلی درجے کا کورس', order: 10, isPublished: true, lessons: [{ title: 'Foundations of Arooz', titleUrdu: 'عروض کی بنیادیں', content: 'Arooz is the Arabic term for the science of meter in classical Arabic and Persian poetry, adopted by Urdu literature.', contentUrdu: 'عروض عربی اصطلاح ہے جو کلاسیکل عربی اور فارسی شاعری میں وزن کے علم کے لیے استعمال ہوتی ہے، جسے اردو ادب نے اپنایا۔', examples: [], duration: '60 min' }] },
    { title: 'Art of Poetry: How to Become a Good Shaer', titleUrdu: 'شاعری کا فن: اچھا شاعر کیسے بنیں', description: 'Premium course: Master the complete art of Urdu poetry composition. Learn from great masters and develop your unique poetic voice with practical exercises, critiques, and personalized feedback.', descriptionUrdu: 'پریمیم کورس: اردو شاعری کے فن میں مہارت حاصل کریں۔ عظیم شاعروں سے سیکھیں اور عملی مشقوں، نقادانہ تبصروں اور ذاتی خوراک سے اپنی منفرد شاعرانہ آواز تیار کریں۔', order: 11, isPublished: true, lessons: [
      { title: 'Module 1: Foundation of Shaeri', titleUrdu: 'ماڈیول 1: شاعری کی بنیادیں', content: 'Understand the essence of Shaeri and what makes a true poet. Deep exploration of the Urdu poetic tradition and the qualities of great poets.', contentUrdu: 'شاعری کا جوہر سمجھیں اور سچے شاعر کی خصوصیات معلوم کریں۔', examples: [], duration: '50 min' },
      { title: 'Module 2: Developing Your Voice', titleUrdu: 'ماڈیول 2: اپنی آواز تیار کریں', content: 'Learn to find your unique poetic voice. Study how great poets expressed their individuality while respecting tradition. Exercises to discover your authentic style.', contentUrdu: 'اپنی منفرد شاعرانہ آواز تلاش کریں اور تیار کریں۔ روایت کا احترام اور اپنی انفرادیت کو ظاہر کریں۔', examples: [{ urdu: 'میرے شاعری میں میری روح بسی ہے', poet: 'مختلف شاعر', translation: 'My soul resides in my poetry' }], duration: '55 min' },
      { title: 'Module 3: Imagery and Symbolism', titleUrdu: 'ماڈیول 3: تصویری کاری اور علامت', content: 'Master the art of using vivid imagery and deeper symbolism in poetry. Learn from the great masters like Ghalib, Iqbal and Faiz. Practice creating powerful metaphors.', contentUrdu: 'شاعری میں حساس تصویریں اور علامات کا استعمال سیکھیں۔', examples: [], duration: '60 min' },
      { title: 'Module 4: Emotion and Expression', titleUrdu: 'ماڈیول 4: جذبات اور اظہار', content: 'The true art of poetry lies in authentic emotional expression. Learn to channel deep feelings into powerful verses. Study emotional resonance in classical and modern poetry.', contentUrdu: 'سچی شاعری میں جذبات کا اصل اظہار کریں۔ گہری احساسات کو طاقتور اشعار میں تبدیل کریں۔', examples: [], duration: '55 min' },
      { title: 'Module 5: Composition Techniques', titleUrdu: 'ماڈیول 5: تالیف کی تکنیکیں', content: 'Learn practical techniques for composing poetry. Study the writing process of master poets. Learn revision, refinement, and polishing of verses.', contentUrdu: 'شاعری لکھنے کی عملی تکنیکیں سیکھیں۔ بڑے شاعروں کے طریقے کا مطالعہ کریں۔', examples: [], duration: '60 min' },
      { title: 'Module 6: Critique and Feedback Workshop', titleUrdu: 'ماڈیول 6: نقادانہ کورس اور خوراک', content: 'Submit your compositions for expert critique. Learn to analyze and improve your own work and that of peers. Develop critical thinking about poetry.', contentUrdu: 'اپنی تالیفات کے لیے ماہرانہ تبصرے حاصل کریں۔ اپنے کام کو بہتر بنانا سیکھیں۔', examples: [], duration: '90 min' },
      { title: 'Module 7: Capstone Project: Your Poetry Collection', titleUrdu: 'ماڈیول 7: اختتامی منصوبہ: آپ کا شاعری مجموعہ', content: 'Create your final poetry collection. Compile your best works, refine them with expert guidance, and prepare them for publication or sharing.', contentUrdu: 'اپنا شاعری کا مجموعہ تیار کریں اور شائع کے لیے تیار ہوں۔', examples: [], duration: '120 min' },
    ] },
  ];
  coursesData.forEach(c => Course.create(c));
  console.log(`${coursesData.length} courses created`);

  // ─── Qafiya ──────────────────────────────────────────────────────────────────
  const qafiyaData = [
    { word: 'jaan',      wordUrdu: 'جان',      meaning: 'life, soul',               meaningUrdu: 'زندگی، روح',          endingSound: 'آن', examples: [{ sher: 'عشق پر زور نہیں ہے یہ وہ آتش غالب', poet: 'مرزا غالب' }],              relatedWords: ['ایمان', 'آسمان', 'نشان'] },
    { word: 'aasman',    wordUrdu: 'آسمان',     meaning: 'sky, heaven',              meaningUrdu: 'آسمان، فلک',          endingSound: 'آن', examples: [{ sher: 'ستاروں سے آگے جہاں اور بھی ہیں', poet: 'علامہ اقبال' }],        relatedWords: ['جہان', 'نشان', 'بیان'] },
    { word: 'nishaan',   wordUrdu: 'نشان',      meaning: 'mark, sign',               meaningUrdu: 'نشان، علامت',         endingSound: 'آن', examples: [],                                                                     relatedWords: ['جان', 'آسمان', 'ارمان'] },
    { word: 'armaan',    wordUrdu: 'ارمان',     meaning: 'longing, wish',            meaningUrdu: 'خواہش، آرزو',         endingSound: 'آن', examples: [{ sher: 'بہت نکلے میرے ارمان لیکن پھر بھی کم نکلے', poet: 'مرزا غالب' }],   relatedWords: ['جان', 'نشان', 'آسمان'] },
    { word: 'yaar',      wordUrdu: 'یار',       meaning: 'friend, beloved',          meaningUrdu: 'دوست، محبوب',         endingSound: 'ار', examples: [{ sher: 'چلے بھی آؤ کہ گلشن کا کاروبار چلے', poet: 'فیض احمد فیض' }], relatedWords: ['بہار', 'اقرار', 'خمار'] },
    { word: 'bahaar',    wordUrdu: 'بہار',      meaning: 'spring season',            meaningUrdu: 'بہار کا موسم',        endingSound: 'ار', examples: [{ sher: 'گلوں میں رنگ بھرے باد نوبہار چلے', poet: 'فیض احمد فیض' }],    relatedWords: ['یار', 'اقرار', 'انتظار'] },
    { word: 'intizaar',  wordUrdu: 'انتظار',    meaning: 'waiting, anticipation',    meaningUrdu: 'انتظار، توقع',        endingSound: 'ار', examples: [],                                                                     relatedWords: ['یار', 'بہار', 'اقرار'] },
    { word: 'iqraar',    wordUrdu: 'اقرار',     meaning: 'confession',               meaningUrdu: 'اعتراف، تسلیم',       endingSound: 'ار', examples: [],                                                                     relatedWords: ['یار', 'انتظار', 'بہار'] },
    { word: 'aab',       wordUrdu: 'آب',        meaning: 'water, luster',            meaningUrdu: 'پانی، چمک',           endingSound: 'آب', examples: [],                                                                     relatedWords: ['کتاب', 'خواب', 'شراب'] },
    { word: 'kitaab',    wordUrdu: 'کتاب',      meaning: 'book',                     meaningUrdu: 'کتاب، نوشتہ',         endingSound: 'آب', examples: [{ sher: 'جیسے سوکھے ہوئے پھول کتابوں میں ملیں', poet: 'احمد فراز' }],  relatedWords: ['خواب', 'شراب', 'آب'] },
    { word: 'khwaab',    wordUrdu: 'خواب',      meaning: 'dream',                    meaningUrdu: 'خواب، سپنا',          endingSound: 'آب', examples: [{ sher: 'اب کے ہم بچھڑے تو شاید کبھی خوابوں میں ملیں', poet: 'احمد فراز' }], relatedWords: ['کتاب', 'شراب', 'آب'] },
    { word: 'sharaab',   wordUrdu: 'شراب',      meaning: 'wine',                     meaningUrdu: 'شراب، مے',            endingSound: 'آب', examples: [{ sher: 'ساری مستی شراب کی سی ہے', poet: 'میر تقی میر' }],           relatedWords: ['خواب', 'کتاب', 'آب'] },
    { word: 'aah',       wordUrdu: 'آہ',        meaning: 'sigh',                     meaningUrdu: 'آہ، سسکی',            endingSound: 'آہ', examples: [{ sher: 'آہ کو چاہیے اک عمر اثر ہونے تک', poet: 'مرزا غالب' }],       relatedWords: ['راہ', 'نگاہ', 'گاہ'] },
    { word: 'raah',      wordUrdu: 'راہ',       meaning: 'path, way',                meaningUrdu: 'راستہ، طریقہ',        endingSound: 'آہ', examples: [],                                                                     relatedWords: ['آہ', 'نگاہ', 'گاہ'] },
    { word: 'nigaah',    wordUrdu: 'نگاہ',      meaning: 'gaze, glance',             meaningUrdu: 'نظر، دیکھنا',         endingSound: 'آہ', examples: [{ sher: 'ہزار بار وہ میری طرف نگاہ کرے', poet: 'مرزا غالب' }],       relatedWords: ['آہ', 'راہ', 'گاہ'] },
    { word: 'haal',      wordUrdu: 'حال',       meaning: 'condition, state',         meaningUrdu: 'حالت، کیفیت',         endingSound: 'ال', examples: [{ sher: 'پتہ پتہ بوٹا بوٹا حال ہمارا جانے ہے', poet: 'میر تقی میر' }], relatedWords: ['سوال', 'خیال', 'جمال'] },
    { word: 'sawaal',    wordUrdu: 'سوال',      meaning: 'question',                 meaningUrdu: 'سوال، پوچھ',          endingSound: 'ال', examples: [],                                                                     relatedWords: ['حال', 'خیال', 'جمال'] },
    { word: 'khayaal',   wordUrdu: 'خیال',      meaning: 'thought, imagination',     meaningUrdu: 'سوچ، تصور',           endingSound: 'ال', examples: [],                                                                     relatedWords: ['حال', 'سوال', 'جمال'] },
    { word: 'jamaal',    wordUrdu: 'جمال',      meaning: 'beauty',                   meaningUrdu: 'خوبصورتی، حسن',       endingSound: 'ال', examples: [],                                                                     relatedWords: ['حال', 'خیال', 'سوال'] },
    { word: 'yaad',      wordUrdu: 'یاد',       meaning: 'memory, remembrance',      meaningUrdu: 'یاداشت، تذکرہ',       endingSound: 'اد', examples: [{ sher: 'ابھی تک یاد ہے مجھ کو وہ پہلی ملاقات', poet: 'ابن انشاء' }],  relatedWords: ['فریاد', 'آزاد', 'شاد'] },
    { word: 'faryaad',   wordUrdu: 'فریاد',     meaning: 'lament, cry for help',     meaningUrdu: 'فریاد، چیخ و پکار',   endingSound: 'اد', examples: [],                                                                     relatedWords: ['یاد', 'آزاد', 'شاد'] },
    { word: 'aazaad',    wordUrdu: 'آزاد',      meaning: 'free, liberated',          meaningUrdu: 'آزاد، حر',            endingSound: 'اد', examples: [],                                                                     relatedWords: ['یاد', 'فریاد', 'شاد'] },
    { word: 'ishq',      wordUrdu: 'عشق',       meaning: 'love, passion',            meaningUrdu: 'محبت، جنون',          endingSound: 'اق', examples: [{ sher: 'عشق پر زور نہیں ہے یہ وہ آتش غالب', poet: 'مرزا غالب' }],  relatedWords: ['شوق', 'ذوق'] },
    { word: 'shauq',     wordUrdu: 'شوق',       meaning: 'passion, enthusiasm',      meaningUrdu: 'شوق، جذبہ',           endingSound: 'اق', examples: [],                                                                     relatedWords: ['عشق', 'ذوق'] },
    { word: 'zauq',      wordUrdu: 'ذوق',       meaning: 'taste, aesthetic sense',   meaningUrdu: 'ذوق، پسند',           endingSound: 'اق', examples: [],                                                                     relatedWords: ['عشق', 'شوق'] },
    { word: 'kaam',      wordUrdu: 'کام',       meaning: 'work, desire',             meaningUrdu: 'کام، خواہش',          endingSound: 'ام', examples: [],                                                                     relatedWords: ['نام', 'دام', 'شام'] },
    { word: 'naam',      wordUrdu: 'نام',       meaning: 'name, fame',               meaningUrdu: 'نام، شہرت',           endingSound: 'ام', examples: [],                                                                     relatedWords: ['کام', 'دام', 'شام'] },
    { word: 'shaam',     wordUrdu: 'شام',       meaning: 'evening',                  meaningUrdu: 'شام، سہ پہر',         endingSound: 'ام', examples: [{ sher: 'وہ شام کی روشنی وہ چاند رات', poet: 'ابن انشاء' }],         relatedWords: ['کام', 'نام', 'دام'] },
    { word: 'insaaf',    wordUrdu: 'انصاف',     meaning: 'justice',                  meaningUrdu: 'انصاف، عدل',          endingSound: 'اف', examples: [],                                                                     relatedWords: ['معاف', 'صاف'] },
    { word: 'maaf',      wordUrdu: 'معاف',      meaning: 'forgiven, excused',        meaningUrdu: 'معاف، بخشا',          endingSound: 'اف', examples: [],                                                                     relatedWords: ['انصاف', 'صاف'] },
    { word: 'mulaqaat',  wordUrdu: 'ملاقات',    meaning: 'meeting, encounter',       meaningUrdu: 'ملاقات، میل',         endingSound: 'ات', examples: [{ sher: 'ابھی تک یاد ہے مجھ کو وہ پہلی ملاقات', poet: 'ابن انشاء' }], relatedWords: ['حیات', 'جذبات', 'کائنات'] },
    { word: 'hayaat',    wordUrdu: 'حیات',      meaning: 'life, existence',          meaningUrdu: 'زندگی، وجود',         endingSound: 'ات', examples: [],                                                                     relatedWords: ['ملاقات', 'جذبات', 'کائنات'] },
    { word: 'jazabaat',  wordUrdu: 'جذبات',     meaning: 'emotions, feelings',       meaningUrdu: 'احساسات، جذبے',       endingSound: 'ات', examples: [],                                                                     relatedWords: ['حیات', 'ملاقات', 'کائنات'] },
    { word: 'kainaat',   wordUrdu: 'کائنات',    meaning: 'universe, cosmos',         meaningUrdu: 'کائنات، عالم',        endingSound: 'ات', examples: [],                                                                     relatedWords: ['حیات', 'ملاقات', 'جذبات'] },
    { word: 'dil',       wordUrdu: 'دل',        meaning: 'heart',                    meaningUrdu: 'دل، قلب',             endingSound: 'ل',  examples: [{ sher: 'دلِ ناداں تجھے ہوا کیا ہے', poet: 'مرزا غالب' }],           relatedWords: ['منزل', 'کامل', 'ساحل'] },
    { word: 'gham',      wordUrdu: 'غم',        meaning: 'sorrow, grief',            meaningUrdu: 'غم، دکھ',             endingSound: 'م',  examples: [{ sher: 'اور بھی دکھ ہیں زمانے میں محبت کے سوا', poet: 'فیض احمد فیض' }], relatedWords: ['قدم', 'حرم', 'ستم'] },
    { word: 'raat',      wordUrdu: 'رات',       meaning: 'night',                    meaningUrdu: 'رات، شب',             endingSound: 'ت',  examples: [],                                                                     relatedWords: ['برات', 'بات', 'ذات'] },
    { word: 'zulf',      wordUrdu: 'زلف',       meaning: 'tress, lock of hair',      meaningUrdu: 'زلف، لٹ',             endingSound: 'ف',  examples: [{ sher: 'کون جیتا ہے تری زلف کے سر ہونے تک', poet: 'مرزا غالب' }], relatedWords: ['لطف', 'کشف'] },
    { word: 'wafa',      wordUrdu: 'وفا',       meaning: 'loyalty, faithfulness',    meaningUrdu: 'وفا، وفاداری',        endingSound: 'ا',  examples: [{ sher: 'وفا کیسی کہاں کا عشق جب سر پھوڑنا ٹھہرا', poet: 'احمد فراز' }], relatedWords: ['جفا', 'صفا', 'دعا'] },
    { word: 'dua',       wordUrdu: 'دعا',       meaning: 'prayer, supplication',     meaningUrdu: 'دعا، مناجات',         endingSound: 'ا',  examples: [{ sher: 'لب پے آتی ہے دعا بن کے تمنا میری', poet: 'علامہ اقبال' }],    relatedWords: ['وفا', 'جفا', 'صفا'] },
  ];
  qafiyaData.forEach(q => Qafiya.create(q));
  console.log(`${qafiyaData.length} qafiya entries created`);

  // NOTE: credentials below are for local development only — never use in production
  console.log('\n✅ Seed complete! (development credentials — do NOT use in production)');
  console.log('   Admin: admin@zauqesukhn.com  /  see seed script');
  console.log('   User:  test@zauqesukhn.com   /  see seed script');
  db.close();
}

try {
  seed();
} catch (err) {
  console.error('Seed failed:', err);
  process.exit(1);
}

